// Code generated by protoc-gen-comments. DO NOT EDIT.
// This file consolidates comments from all proto files in this package.

package pbgen

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
)

// Comments maps protobuf descriptor full names to their leading comments
var Comments = map[string]string{
	"redpanda.core.pbgen.RPCAuthZLevel": "The authentication level for this handler.",
	"redpanda.core.pbgen.RPCOptions.authz": `The authentication level required to invoke the handler. Must be
 specified.

 APIs should default to SUPERUSER, if you'd like to create an admin API at
 another level, please consult the Redpanda core team first.`,
	"redpanda.core.pbgen.RPCOptions.http_route": `The alternative HTTP route to use for this handler. This is used to give
 "prettier" HTTP routes to the user. This is an additional route used to
 alias the ConnectRPC route that is automatically generated.`,
}

// GetComment returns the comment for a descriptor by its full name
func GetComment(fullName string) string {
	return Comments[fullName]
}

// GetCommentForField returns the comment for a field descriptor
func GetCommentForField(fd protoreflect.FieldDescriptor) string {
	return GetComment(string(fd.FullName()))
}

// GetCommentForMessage returns the comment for a message descriptor
func GetCommentForMessage(md protoreflect.MessageDescriptor) string {
	return GetComment(string(md.FullName()))
}

// GetCommentForEnum returns the comment for an enum descriptor
func GetCommentForEnum(ed protoreflect.EnumDescriptor) string {
	return GetComment(string(ed.FullName()))
}

// GetCommentForEnumValue returns the comment for an enum value descriptor
func GetCommentForEnumValue(evd protoreflect.EnumValueDescriptor) string {
	return GetComment(string(evd.FullName()))
}
